# Generated by Django 6.1 on 2026-08-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestionai',
            name='suggestion_category',
            field=models.CharField(max_length=100),
        ),
    ]
