# Generated by Django 6.1 on 2026-08-31 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='rol',
            new_name='role',
        ),
    ]
